### ISSUE TITLE
Action failed with no errors

### ISSUE THREAD

**Issue by cdavernas** [alex-ac/github-action-ssh-docker-compose#1]
## Description

When I try to run the SSH docker compose action, the pipeline fails, without giving me any pointers on what went wrong.

## Expected Behavior

The pipeline works, the repo is cloned on the remote machine and the solution has been built and is running on docker-compose.

## Actual Behavior

The pipeline fails, with the following logs:

```
>> [local] Packing workspace into archive to transfer onto remote machine.
...
>> [local] Launching ssh agent.
Agent pid 11
>> [local] Killing ssh agent.
unset SSH_AUTH_SOCK;
unset SSH_AGENT_PID;
echo Agent pid 11 killed;
>> [local] Removing workspace archive.
Enter passphrase for /dev/fd/63: 
```

**Comment by alex-ac** [comment]
The action has started ssh-agent. After that it tried to load your SSH key.

However, Your SSH key is password-encrypted, so you see `Enter passphrase for /dev/fd/63:` there.

This action does not support password-encrypted keys for several reasons:
1. There is simply no easy and secure way to pass that password to the ssh-add.
2. The SSH key for this action should be keeped in the github secrets. Keeping the password next to the key will not make anything safer.

So, replace the ssh key in the secret with a key without password and it will work as intended. For safety concerns please consider using a separate key pair for this action and creating a separate user on the managed server which can access only it's own home directory and docker.

**Comment by cdavernas** [comment]
Yup, that did it, thank you very much!
