### ISSUE TITLE
Problem with private key

### ISSUE THREAD

**Issue by fabdelgado** [alex-ac/github-action-ssh-docker-compose#4]
When I run the github action, output in console is:

>> [local] Packing workspace into archive to transfer onto remote machine.
Error loading key "/dev/fd/63": invalid format
./
>> [local] Launching ssh agent.
Agent pid 10
>> [local] Killing ssh agent.
unset SSH_AUTH_SOCK;
unset SSH_AGENT_PID;
echo Agent pid 10 killed;
>> [local] Removing workspace archive.

**Comment by Ma100Dev** [comment]
Your key is probably malformed. Did you include `-----BEGIN OPENSSH PRIVATE KEY-----` and `-----END OPENSSH PRIVATE KEY-----`? This was the problem for me.

**Comment by fabdelgado** [comment]
@Ma100Dev Yes, it's necessary add that, I added to Readme for new users.

**Comment by Ma100Dev** [comment]
So is the problem resolved or still open considering that?

**Comment by fabdelgado** [comment]
yes problem is resolved!, thanks!
